project:
  type: website
website:
  title: "TRUDI 2026"
  navbar:
    logo: assets/TRUDI2026_notext_256x256.png
    left:
      - href: index.qmd
        text: Home
      - program.qmd
      - participants.qmd
      - venue.qmd
      - organizers.qmd
      - snubic.qmd
      - universe.qmd
  page-footer:
    right:
      - href: organizers.qmd
        text: Contact
      - href: https://uni-koeln.de/impressum
        text: Imprint
format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    include-in-header: |
      <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
execute:
  freeze: auto
