project:
  type: website
website:
  title: "TRUDI 2026"
  navbar:
    logo: assets/trixi.png
    left:
      - href: index.qmd
        text: Home
      - program.qmd
      - venue.qmd
      - organizers.qmd
      - snubic.qmd
  page-footer:
    right:
      - href: https://uni-koeln.de/impressum
        text: Imprint
format:
  html:
    theme: cosmo
    toc: true
execute:
  freeze: auto
